version: '3.9'
services:
  node:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - type: bind
        source: $PWD
        target: /usr/src/app
    networks:
      - espresso
  gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 43210:3000
    volumes:
      - type: bind
        source: $PWD/src
        target: /usr/src/app/src
    networks:
      - espresso
networks:
  espresso:
    external: true
